version: '3.8'
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: 'YourStrong!Passw0rd'
      ACCEPT_EULA: 'Y'
    ports: [ '1433:1433' ]
  redis:
    image: redis:7
    ports: [ '6379:6379' ]
